In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.metrics import mean_squared_error

In [2]:
# Load datasets
tournament_df = pd.read_csv("Dataset/Tournament Matchups.csv")
kenpom_df = pd.read_csv("Dataset/KenPom Barttorvik.csv")

# Basic inspection
print("Tournament Matchups shape:", tournament_df.shape)
print("KenPom Barttorvik shape:", kenpom_df.shape)

tournament_df.head()

Tournament Matchups shape: (2140, 8)
KenPom Barttorvik shape: (1147, 103)

   YEAR  BY YEAR NO  TEAM NO         TEAM  SEED  ROUND  CURRENT ROUND  SCORE
0  2025        2140     1141       Auburn     1      4             64     83
1  2025        2139     1145  Alabama St.    16     64             64     63
2  2025        2138     1119   Louisville     8     64             64     75
3  2025        2137     1134    Creighton     9     32             64     89
4  2025        2136     1114     Michigan     5     16             64     68

In [3]:
kenpom_df.head()

,YEAR,CONF,CONF ID,QUAD NO,QUAD ID,TEAM NO,TEAM ID,TEAM,SEED,ROUND,...,BADJT RANK,AVG HGT RANK,EFF HGT RANK,EXP RANK,TALENT RANK,FT% RANK,OP FT% RANK,PPPO RANK,PPPD RANK,ELITE SOS RANK
0,2025,MAC,17,66,2,1147,2,Akron,13,64,...,19,361,364,73,149,86,239,25,145,305
1,2025,SEC,28,66,2,1146,3,Alabama,2,8,...,1,57,4,261,32,211,92,9,174,1
2,2025,SWAC,31,68,4,1145,4,Alabama St.,16,64,...,154,285,239,83,251,270,61,227,147,253
3,2025,Pat,25,66,2,1144,6,American,16,68,...,349,303,248,181,364,58,34,218,163,329
4,2025,B12,7,66,2,1143,8,Arizona,4,16,...,52,74,129,225,16,18,143,25,87,3

In [4]:
# missing values in tournament_df
print(tournament_df.isnull().sum())

# missing values in kenpom_df
print(kenpom_df.isnull().sum())

YEAR             0
BY YEAR NO       0
TEAM NO          0
TEAM             0
SEED             0
ROUND            0
CURRENT ROUND    0
SCORE            0
dtype: int64
YEAR              0
CONF              0
CONF ID           0
QUAD NO           0
QUAD ID           0
                 ..
FT% RANK          0
OP FT% RANK       0
PPPO RANK         0
PPPD RANK         0
ELITE SOS RANK    0
Length: 103, dtype: int64

In [5]:
# distribution of scores
tournament_df["SCORE"].describe()

count    2140.000000
mean       69.821963
std        12.003840
min        29.000000
25%        61.000000
50%        70.000000
75%        78.000000
max       113.000000
Name: SCORE, dtype: float64

In [6]:
# tournament years
print(tournament_df["YEAR"].unique())
# kenpom years
print(kenpom_df["YEAR"].unique())

[2025 2024 2023 2022 2021 2019 2018 2017 2016 2015 2014 2013 2012 2011
 2010 2009 2008]
[2025 2024 2023 2022 2021 2019 2018 2017 2016 2015 2014 2013 2012 2011
 2010 2009 2008]

In [7]:
# team names in each dataset
print(tournament_df["TEAM"].unique()[:20])

print(kenpom_df["TEAM"].unique()[:20])

['Auburn' 'Alabama St.' 'Louisville' 'Creighton' 'Michigan' 'UC San Diego'
 'Texas A&M' 'Yale' 'Mississippi' 'North Carolina' 'Iowa St.' 'Lipscomb'
 'Marquette' 'New Mexico' 'Michigan St.' 'Bryant' 'Florida' 'Norfolk St.'
 'Connecticut' 'Oklahoma']
['Akron' 'Alabama' 'Alabama St.' 'American' 'Arizona' 'Arkansas' 'Auburn'
 'Baylor' 'Bryant' 'BYU' 'Clemson' 'Colorado St.' 'Connecticut'
 'Creighton' 'Drake' 'Duke' 'Florida' 'Georgia' 'Gonzaga' 'Grand Canyon']

In [8]:
# merge on year and team
merged_df = pd.merge(
    tournament_df,
    kenpom_df,
    on=["YEAR", "TEAM"],
    how="inner"
)

print(merged_df.shape)

merged_df.head()

(2131, 109)

,YEAR,BY YEAR NO,TEAM NO_x,TEAM,SEED_x,ROUND_x,CURRENT ROUND,SCORE,CONF,CONF ID,...,BADJT RANK,AVG HGT RANK,EFF HGT RANK,EXP RANK,TALENT RANK,FT% RANK,OP FT% RANK,PPPO RANK,PPPD RANK,ELITE SOS RANK
0,2025,2140,1141,Auburn,1,4,64,83,SEC,28,...,143,22,66,20,90,116,264,3,59,2
1,2025,2139,1145,Alabama St.,16,64,64,63,SWAC,31,...,154,285,239,83,251,270,61,227,147,253
2,2025,2138,1119,Louisville,8,64,64,75,ACC,2,...,92,65,58,23,129,104,143,43,35,59
3,2025,2137,1134,Creighton,9,32,64,89,BE,8,...,187,7,3,219,30,140,143,84,81,52
4,2025,2136,1114,Michigan,5,16,64,68,B10,6,...,65,5,2,116,38,162,239,94,47,22

In [9]:
# initial feature columns
features = ["SEED_x", "BADJ O", "BADJ D", "BARTHAG", "EXP", "TALENT"]

X = merged_df[features]
# for now score, will change to margin of victory later
y = merged_df["SCORE"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(X_train.shape)
print(X_test.shape)

(1704, 6)
(427, 6)

In [10]:
# normalize
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [11]:
# mlp model
model = keras.Sequential([ 
    layers.Dense(64, activation="relu", input_shape=(X_train_scaled.shape[1],)), 
    layers.Dense(32, activation="relu"), 
    layers.Dense(16, activation="relu"), 
    layers.Dropout(0.2), 
    layers.Dense(8, activation="relu"), 
    layers.Dense(1) 
])

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [12]:
model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss="mse",
    metrics=["mae"]
)

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,201 (12.50 KB)

 Trainable params: 3,201 (12.50 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
history = model.fit(
    X_train_scaled,
    y_train,
    epochs=100,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

Epoch 1/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4958.1528 - mae: 69.4199 - val_loss: 4837.0420 - val_mae: 68.3779
Epoch 2/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - loss: 4449.4126 - mae: 65.5610 - val_loss: 2804.5811 - val_mae: 50.7033
Epoch 3/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 769us/step - loss: 1766.2336 - mae: 38.2158 - val_loss: 646.0477 - val_mae: 21.1825
Epoch 4/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 768us/step - loss: 733.0489 - mae: 22.4414 - val_loss: 412.0796 - val_mae: 16.6212
Epoch 5/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 745us/step - loss: 503.2830 - mae: 18.3578 - val_loss: 293.8941 - val_mae: 13.9285
Epoch 6/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 772us/step - loss: 364.4919 - mae: 14.9368 - val_loss: 231.6570 - val_mae: 12.3194
Epoch 7/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 778us/step - loss: 344.3739 - mae: 14.8337 - val_loss: 201.2748 - val_mae: 11.4308
Epoch 8/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 749us/step - loss: 294.0401 - mae: 13.3534 - val_loss: 197.3919 - val_mae: 11.2957
Epoch 9/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 744us/step - loss: 288.8826 - mae: 13.4940 - val_loss: 172.9316 - val_mae: 10.6023
Epoch 10/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 784us/step - loss: 276.6415 - mae: 13.1455 - val_loss: 170.5552 - val_mae: 10.5288
Epoch 11/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - loss: 243.3810 - mae: 12.2819 - val_loss: 172.7818 - val_mae: 10.5607
Epoch 12/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - loss: 239.9718 - mae: 12.3597 - val_loss: 173.3673 - val_mae: 10.5299
Epoch 13/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - loss: 231.8202 - mae: 12.2127 - val_loss: 169.3188 - val_mae: 10.3977
Epoch 14/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - loss: 211.6166 - mae: 11.3811 - val_loss: 179.6764 - val_mae: 10.6494
Epoch 15/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step - loss: 223.0037 - mae: 11.5031 - val_loss: 173.9612 - val_mae: 10.4557
Epoch 16/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step - loss: 210.8415 - mae: 11.3475 - val_loss: 192.2157 - val_mae: 10.9148
Epoch 17/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 202.0633 - mae: 11.2907 - val_loss: 202.5507 - val_mae: 11.2869
Epoch 18/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - loss: 201.5825 - mae: 11.2814 - val_loss: 180.2846 - val_mae: 10.6454
Epoch 19/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - loss: 196.1863 - mae: 10.9064 - val_loss: 174.7819 - val_mae: 10.4371
Epoch 20/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - loss: 193.9678 - mae: 11.0763 - val_loss: 201.0016 - val_mae: 11.1731
Epoch 21/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - loss: 182.0858 - mae: 10.6084 - val_loss: 208.0959 - val_mae: 11.4215
Epoch 22/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 181.5679 - mae: 10.4611 - val_loss: 214.2857 - val_mae: 11.5946
Epoch 23/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - loss: 193.9082 - mae: 10.7564 - val_loss: 203.9153 - val_mae: 11.2829
Epoch 24/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - loss: 176.9718 - mae: 10.5080 - val_loss: 232.3092 - val_mae: 12.1211
Epoch 25/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - loss: 168.4388 - mae: 10.2389 - val_loss: 207.4434 - val_mae: 11.4032
Epoch 26/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 766us/step - loss: 173.2824 - mae: 10.3971 - val_loss: 244.6452 - val_mae: 12.4631
Epoch 27/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 751us/step - loss: 166.8598 - mae: 10.1984 - val_loss: 241.9527 - val_mae: 12.4180
Epoch 28/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 762us/step - loss: 156.2807 - mae: 9.9039 - val_loss: 266.5654 - val_mae: 13.1098
Epoch 29/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 764us/step - loss: 153.9485 - mae: 9.6968 - val_loss: 226.7011 - val_mae: 11.9705
Epoch 30/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 762us/step - loss: 159.6597 - mae: 9.8573 - val_loss: 281.5605 - val_mae: 13.4958
Epoch 31/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 780us/step - loss: 157.5836 - mae: 9.7516 - val_loss: 282.1312 - val_mae: 13.5476
Epoch 32/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 770us/step - loss: 161.4092 - mae: 10.0090 - val_loss: 310.7616 - val_mae: 14.3030
Epoch 33/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 766us/step - loss: 156.9621 - mae: 9.7913 - val_loss: 281.3189 - val_mae: 13.4915
Epoch 34/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 778us/step - loss: 150.1645 - mae: 9.6801 - val_loss: 292.6900 - val_mae: 13.7995
Epoch 35/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - loss: 144.9090 - mae: 9.5566 - val_loss: 286.8140 - val_mae: 13.6562
Epoch 36/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 786us/step - loss: 149.7517 - mae: 9.6418 - val_loss: 289.9609 - val_mae: 13.7101
Epoch 37/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - loss: 145.4944 - mae: 9.3841 - val_loss: 275.8715 - val_mae: 13.3969
Epoch 38/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 807us/step - loss: 145.3289 - mae: 9.5352 - val_loss: 320.9108 - val_mae: 14.5504
Epoch 39/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - loss: 158.4612 - mae: 9.7183 - val_loss: 326.7958 - val_mae: 14.8065
Epoch 40/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - loss: 153.8109 - mae: 9.7300 - val_loss: 268.7289 - val_mae: 13.1391
Epoch 41/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - loss: 163.2307 - mae: 9.7770 - val_loss: 332.3060 - val_mae: 14.8826
Epoch 42/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 812us/step - loss: 137.9184 - mae: 9.1968 - val_loss: 316.2487 - val_mae: 14.5017
Epoch 43/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - loss: 153.0256 - mae: 9.6439 - val_loss: 345.0059 - val_mae: 15.3123
Epoch 44/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 798us/step - loss: 140.5872 - mae: 9.4903 - val_loss: 321.9359 - val_mae: 14.6695
Epoch 45/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - loss: 147.2445 - mae: 9.6074 - val_loss: 343.3144 - val_mae: 15.2743
Epoch 46/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - loss: 157.3260 - mae: 9.7812 - val_loss: 337.5023 - val_mae: 15.0969
Epoch 47/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - loss: 152.4804 - mae: 9.5606 - val_loss: 336.3394 - val_mae: 15.0334
Epoch 48/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - loss: 132.7793 - mae: 9.1350 - val_loss: 357.1624 - val_mae: 15.6204
Epoch 49/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - loss: 135.2729 - mae: 9.0612 - val_loss: 336.3426 - val_mae: 15.0314
Epoch 50/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - loss: 155.6662 - mae: 9.6920 - val_loss: 324.8032 - val_mae: 14.7145
Epoch 51/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - loss: 133.1994 - mae: 9.1736 - val_loss: 337.3788 - val_mae: 15.0739
Epoch 52/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - loss: 154.0261 - mae: 9.5737 - val_loss: 324.0284 - val_mae: 14.6547
Epoch 53/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 772us/step - loss: 147.2387 - mae: 9.6066 - val_loss: 304.6985 - val_mae: 14.1699
Epoch 54/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 781us/step - loss: 149.6330 - mae: 9.6079 - val_loss: 327.1947 - val_mae: 14.7942
Epoch 55/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - loss: 134.0020 - mae: 9.1282 - val_loss: 310.4794 - val_mae: 14.3250
Epoch 56/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 969us/step - loss: 147.3612 - mae: 9.6110 - val_loss: 327.4239 - val_mae: 14.8376
Epoch 57/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - loss: 151.1490 - mae: 9.6233 - val_loss: 288.5172 - val_mae: 13.7574
Epoch 58/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 777us/step - loss: 141.7729 - mae: 9.4375 - val_loss: 343.8088 - val_mae: 15.2957
Epoch 59/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 766us/step - loss: 135.8241 - mae: 9.3000 - val_loss: 353.9885 - val_mae: 15.5486
Epoch 60/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 777us/step - loss: 139.9230 - mae: 9.1960 - val_loss: 358.5482 - val_mae: 15.6760
Epoch 61/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 763us/step - loss: 150.2287 - mae: 9.5824 - val_loss: 344.4606 - val_mae: 15.2730
Epoch 62/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 770us/step - loss: 141.2091 - mae: 9.3106 - val_loss: 347.7705 - val_mae: 15.3640
Epoch 63/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 779us/step - loss: 162.5914 - mae: 10.0876 - val_loss: 361.8565 - val_mae: 15.7415
Epoch 64/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 782us/step - loss: 137.5641 - mae: 9.3862 - val_loss: 370.0237 - val_mae: 15.9492
Epoch 65/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 786us/step - loss: 138.1153 - mae: 9.3402 - val_loss: 340.3181 - val_mae: 15.1488
Epoch 66/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 782us/step - loss: 137.3046 - mae: 9.2218 - val_loss: 331.8224 - val_mae: 14.9115
Epoch 67/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 762us/step - loss: 144.1445 - mae: 9.5133 - val_loss: 337.8128 - val_mae: 15.1009
Epoch 68/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 776us/step - loss: 146.6742 - mae: 9.4214 - val_loss: 321.6463 - val_mae: 14.6490
Epoch 69/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 753us/step - loss: 154.0947 - mae: 9.7603 - val_loss: 344.0037 - val_mae: 15.2765
Epoch 70/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 764us/step - loss: 143.1609 - mae: 9.2384 - val_loss: 321.5198 - val_mae: 14.6550
Epoch 71/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 766us/step - loss: 139.5912 - mae: 9.3096 - val_loss: 365.2000 - val_mae: 15.8599
Epoch 72/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 769us/step - loss: 139.8297 - mae: 9.3552 - val_loss: 315.1408 - val_mae: 14.4530
Epoch 73/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - loss: 133.9014 - mae: 9.1587 - val_loss: 343.4457 - val_mae: 15.2645
Epoch 74/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 766us/step - loss: 144.0313 - mae: 9.4025 - val_loss: 334.4477 - val_mae: 15.0091
Epoch 75/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 768us/step - loss: 137.6108 - mae: 9.2189 - val_loss: 336.6846 - val_mae: 15.0659
Epoch 76/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 759us/step - loss: 140.5441 - mae: 9.1181 - val_loss: 327.9322 - val_mae: 14.8463
Epoch 77/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 765us/step - loss: 134.3198 - mae: 9.0941 - val_loss: 339.5732 - val_mae: 15.1536
Epoch 78/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 763us/step - loss: 134.3582 - mae: 9.1632 - val_loss: 348.3612 - val_mae: 15.4264
Epoch 79/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 757us/step - loss: 134.8957 - mae: 9.1814 - val_loss: 308.5629 - val_mae: 14.2503
Epoch 80/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 777us/step - loss: 149.3041 - mae: 9.7177 - val_loss: 369.3670 - val_mae: 15.9847
Epoch 81/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 775us/step - loss: 140.6985 - mae: 9.4000 - val_loss: 309.7554 - val_mae: 14.3351
Epoch 82/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 773us/step - loss: 145.7508 - mae: 9.3880 - val_loss: 396.0638 - val_mae: 16.6360
Epoch 83/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 773us/step - loss: 142.3306 - mae: 9.3208 - val_loss: 320.7259 - val_mae: 14.6172
Epoch 84/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 760us/step - loss: 153.5282 - mae: 9.6141 - val_loss: 324.9390 - val_mae: 14.7561
Epoch 85/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 768us/step - loss: 151.3468 - mae: 9.5800 - val_loss: 365.7758 - val_mae: 15.8350
Epoch 86/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 757us/step - loss: 156.2159 - mae: 9.8907 - val_loss: 305.7558 - val_mae: 14.1800
Epoch 87/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 766us/step - loss: 144.0377 - mae: 9.3230 - val_loss: 382.9984 - val_mae: 16.3079
Epoch 88/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 778us/step - loss: 137.9126 - mae: 9.3008 - val_loss: 343.7901 - val_mae: 15.2571
Epoch 89/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 769us/step - loss: 142.6908 - mae: 9.3687 - val_loss: 354.4211 - val_mae: 15.5269
Epoch 90/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 763us/step - loss: 135.3997 - mae: 9.0886 - val_loss: 374.7497 - val_mae: 16.1315
Epoch 91/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - loss: 142.0294 - mae: 9.2252 - val_loss: 351.2912 - val_mae: 15.4620
Epoch 92/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - loss: 137.5940 - mae: 9.1176 - val_loss: 380.7480 - val_mae: 16.2019
Epoch 93/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 133.2738 - mae: 9.0883 - val_loss: 288.7378 - val_mae: 13.6760
Epoch 94/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - loss: 148.0120 - mae: 9.4471 - val_loss: 360.5370 - val_mae: 15.7043
Epoch 95/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - loss: 144.8614 - mae: 9.3239 - val_loss: 336.0966 - val_mae: 15.0135
Epoch 96/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - loss: 133.7585 - mae: 9.1105 - val_loss: 343.6816 - val_mae: 15.2625
Epoch 97/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - loss: 134.8811 - mae: 9.2216 - val_loss: 333.5785 - val_mae: 14.9764
Epoch 98/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - loss: 136.0786 - mae: 9.0857 - val_loss: 370.4786 - val_mae: 15.9982
Epoch 99/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 784us/step - loss: 138.4112 - mae: 9.3079 - val_loss: 360.6505 - val_mae: 15.7083
Epoch 100/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 772us/step - loss: 141.7039 - mae: 9.4345 - val_loss: 352.9842 - val_mae: 15.4931

In [14]:
test_loss, test_mae = model.evaluate(X_test_scaled, y_test)

print("Test MSE:", test_loss)
print("Test MAE:", test_mae)

14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 740us/step - loss: 284.8843 - mae: 14.5091
Test MSE: 299.2200927734375
Test MAE: 14.792155265808105

In [16]:
predictions = model.predict(X_test_scaled)
print(predictions[:10])

14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step
[[61.464012]
 [52.375225]
 [50.81779 ]
 [47.086613]
 [54.890625]
 [53.576004]
 [53.51561 ]
 [55.49841 ]
 [53.7211  ]
 [56.828484]]